Repository ScottLogic/StockFlux, pull requests merged in 2019-11, with the labels that each got.

#1340 1333: New Screenshots for Readme.md mathcing UX refactor v1.0
  README.md
  stockflux.png
Labels: Docs

#1360 UX - Change existing windows to new colours
  packages/stockflux-bitflux/src/assets/styles/variables.css
  packages/stockflux-chart/src/styles/app.css
  packages/stockflux-components/src/index.css
Labels: UX

#1347 1342: (Watchlist) Highlight app icons if an app is open
  packages/stockflux-components/src/components/buttons/borderless-buttons/app-shortcuts/Chart.js
  packages/stockflux-components/src/components/buttons/borderless-buttons/app-shortcuts/News.js
  packages/stockflux-components/src/components/buttons/borderless-buttons/app-shortcuts/Watchlist.js
  packages/stockflux-core/src/index.js
  packages/stockflux-core/src/openfin-api-utils/openfinApiHelpers.js
  packages/stockflux-watchlist/src/components/watchlist-card/WatchlistCard.css
  packages/stockflux-watchlist/src/components/watchlist-card/WatchlistCard.js
  packages/stockflux-watchlist/src/reducers/open-apps/Action.js
  packages/stockflux-watchlist/src/reducers/open-apps/OpenApps.js
Labels: UX

#1356 News: Change layout to new ux standard
  packages/stockflux-components/src/index.css
  packages/stockflux-news/src/App.css
  packages/stockflux-news/src/App.js
  packages/stockflux-news/src/components/news-item/NewsItem.css
  packages/stockflux-news/src/index.css
Labels: UX

#1367 Preview Window - Update to match UX designs
  packages/stockflux-watchlist/public/preview-chart.html
Labels: UX

#1369 UX refactor dialog box
  packages/stockflux-components/src/components/Titlebar/Titlebar.js
  packages/stockflux-components/src/components/buttons/dialog-button/DialogButton.css
  packages/stockflux-components/src/components/buttons/dialog-button/DialogButton.js
  packages/stockflux-components/src/components/popups/ConfirmationWindow.js
  packages/stockflux-components/src/components/popups/PopupWindow.js
  packages/stockflux-components/src/index.css
  packages/stockflux-launcher/public/popupWindow.css
  packages/stockflux-launcher/src/App.css
Labels: UX

#1364 Watchlist - Change drag functionality based on drag start location
  packages/stockflux-watchlist/public/delete-symbol.html
  packages/stockflux-watchlist/src/components/watchlist-card/WatchlistCard.js
  packages/stockflux-watchlist/src/components/watchlist/PreviewOptions.js
  packages/stockflux-watchlist/src/components/watchlist/Watchlist.js
Labels: UX

#1386 run npm audit fix
  package-lock.json
  packages/stockflux-launcher/package-lock.json
Labels: Securities Master
